#!/bin/bash

currentDate=$(date +%F)
filePath="backup$currentDate.sql"
mysqldump --single-transaction -u UserExamDB --password='1234' "ExamDB" > $filePath

if [ -f /var/backups/db_web/backup*.sql ]; then
	echo "delete file backup"
	sudo rm /var/backups/db_web/backup*.sql
fi

sudo mv $filePath /var/backups/db_web/
echo $(date) > /var/backups/db_web/db_backup.log
exit
