#!/bin/bash

currentDate=$(date+%F)
filePath="backup$currentDate.sql"
mysqldump â--single-transaction â-u UserExamDB â--password='1234' "ExamDB" > $filePath

i f [â-f /var/backups/db_web/backup*.sql ]; then
echo "delete file backup "
rm /var/backups/db_web/backup*.sql
fi

mv $filePath /var/backups/db_web/
exit
